# alertmanager.yml
global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.example.com:587"
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "alertmanager"
  smtp_auth_password: "password" # Use environment variables in production

route:
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "slack-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "admin@example.com"
        send_resolved: true

  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL"
        channel: "#alerts"
        send_resolved: true
        title: "{{ .GroupLabels.alertname }}"
        text: "{{ .CommonAnnotations.description }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]
