# otel-collector-config.yaml

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 512
  resourcedetection:
    detectors: [env, system]
    timeout: 5s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "pulseguard"

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "pulseguard"
    labels:
      resource:
        service.name: "service_name"
        service.namespace: "service_namespace"
        service.instance.id: "service_instance_id"
      attributes:
        level: "log.level"
        traceID: "trace_id"
        spanID: "span_id"

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/tempo, logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [loki, logging]
