global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pulseguard"
    static_configs:
      # - targets: ["host.docker.internal:9464"] # For MacOS
      # - targets: ["app:8080"] # For Linux
      - targets: ["go-backend:8080"]
        labels:
          service: "pulseguard"

  - job_name: "otel-collector"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["otel-collector:8889"]
        labels:
          service: "otel-collector"

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:8889"]
        labels:
          service: "prometheus"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert.rules"
